name: SonarCloud Analysis for Cpp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CPP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Download and install SonarScanner
        run: |
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.0.4796.zip" -OutFile "sonar-scanner-cli.zip"
          Expand-Archive -Path "sonar-scanner-cli.zip" -DestinationPath "sonar-scanner-cli"
          Remove-Item "sonar-scanner-cli.zip"
          $env:PATH += ";${{ github.workspace }}\sonar-scanner-cli\sonar-scanner-7.0.0.4796\bin"

      - name: Download and install Build Wrapper
        run: |
          Invoke-WebRequest -Uri "https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip" -OutFile "build-wrapper-win-x86.zip"
          Expand-Archive -Path "build-wrapper-win-x86.zip" -DestinationPath "build-wrapper-win-x86"
          Remove-Item "build-wrapper-win-x86.zip"

      - name: Clean up build directory
        run: |
          if (Test-Path ${{ github.workspace }}/EclipseCpp/build) {
            Remove-Item -Recurse -Force ${{ github.workspace }}/EclipseCpp/build
          }

      - name: Run Build Wrapper
        run: |
          mkdir ${{ github.workspace }}/EclipseCpp/build
          cmake -S ${{ github.workspace }}/EclipseCpp -B ${{ github.workspace }}/EclipseCpp/build
          cmake --build ${{ github.workspace }}/EclipseCpp/build --clean-first

      - name: SonarCloud C++ Direct Source File Analysis
        run: |
          $sonarScanner = "${{ github.workspace }}\sonar-scanner-cli\sonar-scanner-7.0.0.4796\bin\sonar-scanner.bat"
          & $sonarScanner `
            "-Dsonar.sources=${{ github.workspace }}\EclipseCpp\Cpp\src" `
            "-Dsonar.projectKey=funfizzy_coldbrew-cpp" `
            "-Dsonar.projectName=ColdBrew.Cpp" `
            "-Dsonar.organization=funfizzy" `
            "-Dsonar.host.url=https://sonarcloud.io" `
            "-Dsonar.cfamily.compiler=cl" `
            "-Dsonar.c.file.suffixes=" `
            "-Dsonar.cpp.file.suffixes=" `
            "-Dsonar.objc.file.suffixes="