name: SonarCloud Analysis for Java

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_JAVA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Debug Workspace
        run: |
          echo "Workspace: ${{ github.workspace }}"

      - name: Create directories for testing
        run: |
          $apps = @('blogging-app', 'ordering-app', 'tasking-app')
          foreach ($app in $apps) {
            $fullPath = "${{ github.workspace }}\EclipseJavaEE\$app"
            echo "Creating directory $fullPath"
            mkdir -Force $fullPath
          }

      - name: Build and analyze Java projects (Test without actual builds)
        run: |
          $apps = @('blogging-app', 'ordering-app', 'tasking-app')
          foreach ($app in $apps) {
            $fullPath = "${{ github.workspace }}\EclipseJavaEE\$app"
            echo "Navigating to $fullPath"
            cd $fullPath
            # Simulate mvn commands without actual builds
            echo "Running mvn compile"
            # mvn compile
            echo "Running mvn clean install"
            # mvn clean install
            echo "Running mvn sonar:sonar"
            # mvn sonar:sonar `
            #   -Dsonar.projectKey=funfizzy_coldbrew-java `
            #   -Dsonar.host.url=https://sonarcloud.io `
            #   -Dsonar.login=${{ secrets.SONAR_TOKEN_JAVA }}
          }