name: SonarCloud Analysis for Kotlin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_KT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install SonarScanner
        run: |
          # Download SonarScanner zip file
          curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
          # Extract SonarScanner
          Expand-Archive -Path sonar-scanner-cli.zip -DestinationPath sonar-scanner
          # Remove zip file
          Remove-Item sonar-scanner-cli.zip

      - name: Add directory to PATH
        run: echo "##[add-path]${{ github.workspace }}/sonar-scanner/sonar-scanner-5.0.1.3006-windows/bin/"

      - name: Build and analyze Kotlin code
        run: |
          ${{ github.workspace }}/EclipseKotlin/Kotlin/gradlew build
          ${{ github.workspace }}/sonar-scanner/sonar-scanner-5.0.1.3006-windows/bin/sonar-scanner.bat -D sonar.organization=funfizzy -D sonar.projectKey=funfizzy_coldbrew-kotlin -D sonar.sources=${{ github.workspace }}/EclipseKotlin/Kotlin/src -D sonar.host.url=https://sonarcloud.io -D sonar.language=kotlin -D sonar.projectBaseDir=${{ github.workspace }}/EclipseKotlin/Kotlin